services:
  portfolio:
    container_name: 'portfolio'
    image: 'ghcr.io/mitchellvanwagoner/portfolio:latest'
    restart: 'unless-stopped'
    build: .
    ports:
      - "3000:3000"
    environment:
      - 'NODE_ENV=production'